[build]
  publish = "dist/public"
  command = "npm install && vite build"

[build.environment]
  NODE_VERSION = "20"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: API routes to serverless functions (if you convert the backend)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200